"""init migrate v2

Revision ID: 7274a2cec645
Revises: 
Create Date: 2020-09-10 21:53:36.586231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7274a2cec645'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.Enum('youtube', 'soundcloud', name='musictypeenum'), nullable=True),
    sa.Column('resource_id', sa.String(length=48), nullable=True),
    sa.Column('pin_count', sa.Integer(), nullable=True),
    sa.Column('listen_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_type', 'resource_id')
    )
    op.create_index(op.f('ix_music_item_listen_count'), 'music_item', ['listen_count'], unique=False)
    op.create_index(op.f('ix_music_item_pin_count'), 'music_item', ['pin_count'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('user_pinned_music',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('music_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['music_item_id'], ['music_item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'music_item_id')
    )
    op.create_table('user_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=48), nullable=True),
    sa.Column('expiration', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_token_token'), 'user_token', ['token'], unique=True)
    op.create_index(op.f('ix_user_token_user_id'), 'user_token', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token_user_id'), table_name='user_token')
    op.drop_index(op.f('ix_user_token_token'), table_name='user_token')
    op.drop_table('user_token')
    op.drop_table('user_pinned_music')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_music_item_pin_count'), table_name='music_item')
    op.drop_index(op.f('ix_music_item_listen_count'), table_name='music_item')
    op.drop_table('music_item')
    # ### end Alembic commands ###
